site_name: orthogonium

# Set navigation here
nav:
  - Home: index.md
  - API Reference:
      - orthogonium.layers module: api/layers.md
#  - Tutorials:
#    - "Demo 0: How to use notebook in documentation": notebooks/demo_fake.ipynb
  - Contributing: CONTRIBUTING.md

theme:
  name: "material"
  logo: assets/banner.png
  favicon: assets/banner.png
  palette:
    - scheme: default
      primary: dark
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings
  - mknotebooks

markdown_extensions:
  - footnotes
  - extra
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - codehilite
  - toc:
      baselevel: 1
      permalink: true
      toc_depth: 1-4
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - css/custom.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - js/custom.js

repo_name: "thib-s/orthogonium"
repo_url: "https://github.com/thib-s/orthogonium"
