name: tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build-and-test:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest]

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python-version }}"
          cache: 'pip'

      - name: Install dependencies
        run: |
          set -xe
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
        shell: bash

      - name: Build
        run: |
          set -xe
          python -VV
          python -m pip install .
        shell: bash

      - name: Run tests
        timeout-minutes: 60
        run: |
          set -xe
          python -VV
          python -c "import torch; print(torch.__version__)"
          pytest --cov=orthogonium.layers --cov-report lcov tests
        shell: bash

      - name: Upload Coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
